package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MdlContext generated by hbm2java
 */
@Entity
@Table(name="mdl_context"
    ,catalog="ead_gaire"
    , uniqueConstraints = @UniqueConstraint(columnNames={"contextlevel", "instanceid"}) 
)
public class MdlContext  implements java.io.Serializable {


     private Long id;
     private long contextlevel;
     private byte depth;
     private long instanceid;
     private String path;

    public MdlContext() {
    }

	
    public MdlContext(long contextlevel, byte depth, long instanceid) {
        this.contextlevel = contextlevel;
        this.depth = depth;
        this.instanceid = instanceid;
    }
    public MdlContext(long contextlevel, byte depth, long instanceid, String path) {
       this.contextlevel = contextlevel;
       this.depth = depth;
       this.instanceid = instanceid;
       this.path = path;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="contextlevel", nullable=false)
    public long getContextlevel() {
        return this.contextlevel;
    }
    
    public void setContextlevel(long contextlevel) {
        this.contextlevel = contextlevel;
    }

    
    @Column(name="depth", nullable=false)
    public byte getDepth() {
        return this.depth;
    }
    
    public void setDepth(byte depth) {
        this.depth = depth;
    }

    
    @Column(name="instanceid", nullable=false)
    public long getInstanceid() {
        return this.instanceid;
    }
    
    public void setInstanceid(long instanceid) {
        this.instanceid = instanceid;
    }

    
    @Column(name="path")
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


