package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MdlLrraepMovimentoRobo generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep_mov_robo"
    ,catalog="ead_gaire"
)
public class MdlLrraepMovimentoRobo  implements java.io.Serializable {


     private Long id;
     private String acao;

    public MdlLrraepMovimentoRobo() {
    }

    public MdlLrraepMovimentoRobo(String acao) {
       this.acao = acao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="acao")
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }




}


