package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import java.sql.Timestamp;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MdlLrraepMovimento generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep_movimento"
    ,catalog="ead_gaire"
)
public class MdlLrraepMovimento  implements java.io.Serializable {


     private Long id;
     private MdlUser Usuario;
     private Timestamp data_hora;
     private MdlLrraepMovimentoRobo movimento;
     private String status;

    public MdlLrraepMovimento() {
    }

    public MdlLrraepMovimento(MdlUser Usuario, Timestamp data_hora, MdlLrraepMovimentoRobo movimento, String status) {
       this.Usuario = Usuario;
       this.data_hora = data_hora;
       this.movimento = movimento;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(cascade=CascadeType.ALL, fetch=FetchType.EAGER)
    @JoinColumn(name="usuario")
    public MdlUser getUsuario() {
        return this.Usuario;
    }
    
    public void setUsuario(MdlUser Usuario) {
        this.Usuario = Usuario;
    }

    
    @Column(name="data_hora")
    public Timestamp getData_hora() {
        return this.data_hora;
    }
    
    public void setData_hora(Timestamp data_hora) {
        this.data_hora = data_hora;
    }

@ManyToOne(cascade=CascadeType.ALL, fetch=FetchType.EAGER)
    @JoinColumn(name="movimento_robo")
    public MdlLrraepMovimentoRobo getMovimento() {
        return this.movimento;
    }
    
    public void setMovimento(MdlLrraepMovimentoRobo movimento) {
        this.movimento = movimento;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


