package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MdlLrraepHorario generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep_horario"
    ,catalog="ead_gaire"
)
public class MdlLrraepHorario  implements java.io.Serializable {


     private Long id;
     private String horario;

    public MdlLrraepHorario() {
    }

    public MdlLrraepHorario(String horario) {
       this.horario = horario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="horario")
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }




}


