package lrraep.bean;
// Generated 16/10/2015 21:19:48 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MdlLrraep generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep"
    ,catalog="ead_gaire"
)
public class MdlLrraep  implements java.io.Serializable {


     private Long id;
     private long course;
     private String name;
     private String intro;
     private short introformat;
     private long timecreated;
     private long timemodified;
     private long grade;

    public MdlLrraep() {
    }

    public MdlLrraep(long course, String name, String intro, short introformat, long timecreated, long timemodified, long grade) {
       this.course = course;
       this.name = name;
       this.intro = intro;
       this.introformat = introformat;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.grade = grade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="course", nullable=false)
    public long getCourse() {
        return this.course;
    }
    
    public void setCourse(long course) {
        this.course = course;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="intro", nullable=false)
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }

    
    @Column(name="introformat", nullable=false)
    public short getIntroformat() {
        return this.introformat;
    }
    
    public void setIntroformat(short introformat) {
        this.introformat = introformat;
    }

    
    @Column(name="timecreated", nullable=false)
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }

    
    @Column(name="timemodified", nullable=false)
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }

    
    @Column(name="grade", nullable=false)
    public long getGrade() {
        return this.grade;
    }
    
    public void setGrade(long grade) {
        this.grade = grade;
    }




}


