package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MdlLrraepExecucao generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep_execucao"
    ,catalog="ead_gaire"
)
public class MdlLrraepExecucao  implements java.io.Serializable {


     private Long id;
     private String codigoFonte;
     private Long usuario;
     private Long lrraep;
     private Long tentativa;
     private Boolean concluiu;
     private Long desafio;
     private Byte executado;

    public MdlLrraepExecucao() {
    }

    public MdlLrraepExecucao(String codigoFonte, Long usuario, Long lrraep, Long tentativa, Boolean concluiu, Long desafio, Byte executado) {
       this.codigoFonte = codigoFonte;
       this.usuario = usuario;
       this.lrraep = lrraep;
       this.tentativa = tentativa;
       this.concluiu = concluiu;
       this.desafio = desafio;
       this.executado = executado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="codigo_fonte")
    public String getCodigoFonte() {
        return this.codigoFonte;
    }
    
    public void setCodigoFonte(String codigoFonte) {
        this.codigoFonte = codigoFonte;
    }

    
    @Column(name="usuario")
    public Long getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Long usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="lrraep")
    public Long getLrraep() {
        return this.lrraep;
    }
    
    public void setLrraep(Long lrraep) {
        this.lrraep = lrraep;
    }

    
    @Column(name="tentativa")
    public Long getTentativa() {
        return this.tentativa;
    }
    
    public void setTentativa(Long tentativa) {
        this.tentativa = tentativa;
    }

    
    @Column(name="concluiu")
    public Boolean getConcluiu() {
        return this.concluiu;
    }
    
    public void setConcluiu(Boolean concluiu) {
        this.concluiu = concluiu;
    }

    
    @Column(name="desafio")
    public Long getDesafio() {
        return this.desafio;
    }
    
    public void setDesafio(Long desafio) {
        this.desafio = desafio;
    }

    
    @Column(name="executado")
    public Byte getExecutado() {
        return this.executado;
    }
    
    public void setExecutado(Byte executado) {
        this.executado = executado;
    }




}


