/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lrraep.bean;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 *
 * @author Romero
 */
/**
 * MdlUser generated by hbm2java
 */
@Entity
@Table(name = "mdl_lrraep_sugestao_cenario", catalog = "moodle")
public class MdlLrraepSugestaoCenario implements Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "usuario")
    private MdlUser Usuario;

    @Column(name = "cen_nao_fin")
    private Integer cenario_nao_finalizado;

    @Column(name = "cen_suger")
    private Integer cenario_sugerido;

    @Column(name = "status")
    private String status;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MdlUser getUsuario() {
        return Usuario;
    }

    public void setUsuario(MdlUser Usuario) {
        this.Usuario = Usuario;
    }

    public Integer getCenario_nao_finalizado() {
        return cenario_nao_finalizado;
    }

    public void setCenario_nao_finalizado(Integer cenario_nao_finalizado) {
        this.cenario_nao_finalizado = cenario_nao_finalizado;
    }

    public Integer getCenario_sugerido() {
        return cenario_sugerido;
    }

    public void setCenario_sugerido(Integer cenario_sugerido) {
        this.cenario_sugerido = cenario_sugerido;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MdlLrraepSugestaoCenario other = (MdlLrraepSugestaoCenario) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

}
