package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MdlLrraepSugestaoCenario generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep_sugestao_cenario"
    ,catalog="ead_gaire"
)
public class MdlLrraepSugestaoCenario  implements java.io.Serializable {


     private Long id;
     private MdlUser Usuario;
     private Integer cenario_nao_finalizado;
     private Integer cenario_sugerido;
     private String status;

    public MdlLrraepSugestaoCenario() {
    }

    public MdlLrraepSugestaoCenario(MdlUser Usuario, Integer cenario_nao_finalizado, Integer cenario_sugerido, String status) {
       this.Usuario = Usuario;
       this.cenario_nao_finalizado = cenario_nao_finalizado;
       this.cenario_sugerido = cenario_sugerido;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(cascade=CascadeType.ALL, fetch=FetchType.EAGER)
    @JoinColumn(name="usuario")
    public MdlUser getUsuario() {
        return this.Usuario;
    }
    
    public void setUsuario(MdlUser Usuario) {
        this.Usuario = Usuario;
    }

    
    @Column(name="cen_nao_fin")
    public Integer getCenario_nao_finalizado() {
        return this.cenario_nao_finalizado;
    }
    
    public void setCenario_nao_finalizado(Integer cenario_nao_finalizado) {
        this.cenario_nao_finalizado = cenario_nao_finalizado;
    }

    
    @Column(name="cen_suger")
    public Integer getCenario_sugerido() {
        return this.cenario_sugerido;
    }
    
    public void setCenario_sugerido(Integer cenario_sugerido) {
        this.cenario_sugerido = cenario_sugerido;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


