package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MdlLrraepDesafio generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep_desafio"
    ,catalog="ead_gaire"
)
public class MdlLrraepDesafio  implements java.io.Serializable {


     private Long id;
     private String descricao;
     private Long pontuacao;
     private String nivel;

    public MdlLrraepDesafio() {
    }

    public MdlLrraepDesafio(String descricao, Long pontuacao, String nivel) {
       this.descricao = descricao;
       this.pontuacao = pontuacao;
       this.nivel = nivel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="pontuacao")
    public Long getPontuacao() {
        return this.pontuacao;
    }
    
    public void setPontuacao(Long pontuacao) {
        this.pontuacao = pontuacao;
    }

    
    @Column(name="nivel")
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


