package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import java.sql.Timestamp;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MdlLrraepRank generated by hbm2java
 */
@Entity
@Table(name="mdl_lrraep_rank"
    ,catalog="ead_gaire"
)
public class MdlLrraepRank  implements java.io.Serializable {


     private Long id;
     private MdlUser Usuario;
     private Integer cenario;
     private Timestamp hora_fim;
     private Timestamp hora_inicio;
     private Integer pontos;
     private String status;

    public MdlLrraepRank() {
    }

    public MdlLrraepRank(MdlUser Usuario, Integer cenario, Timestamp hora_fim, Timestamp hora_inicio, Integer pontos, String status) {
       this.Usuario = Usuario;
       this.cenario = cenario;
       this.hora_fim = hora_fim;
       this.hora_inicio = hora_inicio;
       this.pontos = pontos;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(cascade=CascadeType.ALL, fetch=FetchType.EAGER)
    @JoinColumn(name="usuario")
    public MdlUser getUsuario() {
        return this.Usuario;
    }
    
    public void setUsuario(MdlUser Usuario) {
        this.Usuario = Usuario;
    }

    
    @Column(name="cenario")
    public Integer getCenario() {
        return this.cenario;
    }
    
    public void setCenario(Integer cenario) {
        this.cenario = cenario;
    }

    
    @Column(name="hora_fim")
    public Timestamp getHora_fim() {
        return this.hora_fim;
    }
    
    public void setHora_fim(Timestamp hora_fim) {
        this.hora_fim = hora_fim;
    }

    
    @Column(name="hora_ini")
    public Timestamp getHora_inicio() {
        return this.hora_inicio;
    }
    
    public void setHora_inicio(Timestamp hora_inicio) {
        this.hora_inicio = hora_inicio;
    }

    
    @Column(name="pontos")
    public Integer getPontos() {
        return this.pontos;
    }
    
    public void setPontos(Integer pontos) {
        this.pontos = pontos;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


