package lrraep.bean;
// Generated 18/08/2015 18:22:00 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MdlRoleAssignments generated by hbm2java
 */
@Entity
@Table(name="mdl_role_assignments"
    ,catalog="ead_gaire"
)
public class MdlRoleAssignments  implements java.io.Serializable {


     private Long id;
     private String component;
     private long contextid;
     private long itemid;
     private long modifierid;
     private long roleid;
     private long sortorder;
     private long timemodified;
     private long userid;

    public MdlRoleAssignments() {
    }

    public MdlRoleAssignments(String component, long contextid, long itemid, long modifierid, long roleid, long sortorder, long timemodified, long userid) {
       this.component = component;
       this.contextid = contextid;
       this.itemid = itemid;
       this.modifierid = modifierid;
       this.roleid = roleid;
       this.sortorder = sortorder;
       this.timemodified = timemodified;
       this.userid = userid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="component", nullable=false, length=100)
    public String getComponent() {
        return this.component;
    }
    
    public void setComponent(String component) {
        this.component = component;
    }

    
    @Column(name="contextid", nullable=false)
    public long getContextid() {
        return this.contextid;
    }
    
    public void setContextid(long contextid) {
        this.contextid = contextid;
    }

    
    @Column(name="itemid", nullable=false)
    public long getItemid() {
        return this.itemid;
    }
    
    public void setItemid(long itemid) {
        this.itemid = itemid;
    }

    
    @Column(name="modifierid", nullable=false)
    public long getModifierid() {
        return this.modifierid;
    }
    
    public void setModifierid(long modifierid) {
        this.modifierid = modifierid;
    }

    
    @Column(name="roleid", nullable=false)
    public long getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(long roleid) {
        this.roleid = roleid;
    }

    
    @Column(name="sortorder", nullable=false)
    public long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(long sortorder) {
        this.sortorder = sortorder;
    }

    
    @Column(name="timemodified", nullable=false)
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }

    
    @Column(name="userid", nullable=false)
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }




}


