package lrraep.bean;
// Generated 18/08/2015 18:20:23 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MdlUserEnrolments generated by hbm2java
 */
@Entity
@Table(name = "mdl_user_enrolments", catalog = "ead_gaire")
public class MdlUserEnrolments implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;
    @Column(name = "enrolid", nullable = false)
    private long enrolid;
    @Column(name = "modifierid", nullable = false)
    private long modifierid;
    @Column(name = "status", nullable = false)
    private long status;
    @Column(name = "timecreated", nullable = false)
    private long timecreated;
    @Column(name = "timeend", nullable = false)
    private long timeend;
    @Column(name = "timemodified", nullable = false)
    private long timemodified;
    @Column(name = "timestart", nullable = false)
    private long timestart;
    @Column(name = "userid", nullable = false)
    private long userid;

    public MdlUserEnrolments() {
    }

    public MdlUserEnrolments(long enrolid, long modifierid, long status, long timecreated, long timeend, long timemodified, long timestart, long userid) {
        this.enrolid = enrolid;
        this.modifierid = modifierid;
        this.status = status;
        this.timecreated = timecreated;
        this.timeend = timeend;
        this.timemodified = timemodified;
        this.timestart = timestart;
        this.userid = userid;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getEnrolid() {
        return this.enrolid;
    }

    public void setEnrolid(long enrolid) {
        this.enrolid = enrolid;
    }

    public long getModifierid() {
        return this.modifierid;
    }

    public void setModifierid(long modifierid) {
        this.modifierid = modifierid;
    }

    public long getStatus() {
        return this.status;
    }

    public void setStatus(long status) {
        this.status = status;
    }

    public long getTimecreated() {
        return this.timecreated;
    }

    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }

    public long getTimeend() {
        return this.timeend;
    }

    public void setTimeend(long timeend) {
        this.timeend = timeend;
    }

    public long getTimemodified() {
        return this.timemodified;
    }

    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }

    public long getTimestart() {
        return this.timestart;
    }

    public void setTimestart(long timestart) {
        this.timestart = timestart;
    }

    public long getUserid() {
        return this.userid;
    }

    public void setUserid(long userid) {
        this.userid = userid;
    }
}
