package lrraep.bean;
// Generated 16/10/2015 21:32:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MdlUserEnrolments generated by hbm2java
 */
@Entity
@Table(name="mdl_user_enrolments"
    ,catalog="ead_gaire"
)
public class MdlUserEnrolments  implements java.io.Serializable {


     private Long id;
     private long enrolid;
     private long modifierid;
     private long status;
     private long timecreated;
     private long timeend;
     private long timemodified;
     private long timestart;
     private long userid;

    public MdlUserEnrolments() {
    }

    public MdlUserEnrolments(long enrolid, long modifierid, long status, long timecreated, long timeend, long timemodified, long timestart, long userid) {
       this.enrolid = enrolid;
       this.modifierid = modifierid;
       this.status = status;
       this.timecreated = timecreated;
       this.timeend = timeend;
       this.timemodified = timemodified;
       this.timestart = timestart;
       this.userid = userid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="enrolid", nullable=false)
    public long getEnrolid() {
        return this.enrolid;
    }
    
    public void setEnrolid(long enrolid) {
        this.enrolid = enrolid;
    }

    
    @Column(name="modifierid", nullable=false)
    public long getModifierid() {
        return this.modifierid;
    }
    
    public void setModifierid(long modifierid) {
        this.modifierid = modifierid;
    }

    
    @Column(name="status", nullable=false)
    public long getStatus() {
        return this.status;
    }
    
    public void setStatus(long status) {
        this.status = status;
    }

    
    @Column(name="timecreated", nullable=false)
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }

    
    @Column(name="timeend", nullable=false)
    public long getTimeend() {
        return this.timeend;
    }
    
    public void setTimeend(long timeend) {
        this.timeend = timeend;
    }

    
    @Column(name="timemodified", nullable=false)
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }

    
    @Column(name="timestart", nullable=false)
    public long getTimestart() {
        return this.timestart;
    }
    
    public void setTimestart(long timestart) {
        this.timestart = timestart;
    }

    
    @Column(name="userid", nullable=false)
    public long getUserid() {
        return this.userid;
    }
    
    public void setUserid(long userid) {
        this.userid = userid;
    }




}


