package lrraep.bean;
// Generated 25/07/2015 20:45:27 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MdlUser generated by hbm2java
 */
@Entity
@Table(name="mdl_user"
    ,catalog="ead_gaire"
    , uniqueConstraints = @UniqueConstraint(columnNames={"mnethostid", "username"}) 
)
public class MdlUser  implements java.io.Serializable {


     private Long id;
     private String auth;
     private boolean confirmed;
     private boolean policyagreed;
     private boolean deleted;
     private boolean suspended;
     private long mnethostid;
     private String username;
     private String password;
     private String idnumber;
     private String firstname;
     private String lastname;
     private String email;
     private boolean emailstop;
     private String icq;
     private String skype;
     private String yahoo;
     private String aim;
     private String msn;
     private String phone1;
     private String phone2;
     private String institution;
     private String department;
     private String address;
     private String city;
     private String country;
     private String lang;
     private String calendartype;
     private String theme;
     private String timezone;
     private long firstaccess;
     private long lastaccess;
     private long lastlogin;
     private long currentlogin;
     private String lastip;
     private String secret;
     private long picture;
     private String url;
     private String description;
     private byte descriptionformat;
     private boolean mailformat;
     private boolean maildigest;
     private byte maildisplay;
     private boolean autosubscribe;
     private boolean trackforums;
     private long timecreated;
     private long timemodified;
     private long trustbitmask;
     private String imagealt;
     private String lastnamephonetic;
     private String firstnamephonetic;
     private String middlename;
     private String alternatename;

    public MdlUser() {
    }

	
    public MdlUser(String auth, boolean confirmed, boolean policyagreed, boolean deleted, boolean suspended, long mnethostid, String username, String password, String idnumber, String firstname, String lastname, String email, boolean emailstop, String icq, String skype, String yahoo, String aim, String msn, String phone1, String phone2, String institution, String department, String address, String city, String country, String lang, String calendartype, String theme, String timezone, long firstaccess, long lastaccess, long lastlogin, long currentlogin, String lastip, String secret, long picture, String url, byte descriptionformat, boolean mailformat, boolean maildigest, byte maildisplay, boolean autosubscribe, boolean trackforums, long timecreated, long timemodified, long trustbitmask) {
        this.auth = auth;
        this.confirmed = confirmed;
        this.policyagreed = policyagreed;
        this.deleted = deleted;
        this.suspended = suspended;
        this.mnethostid = mnethostid;
        this.username = username;
        this.password = password;
        this.idnumber = idnumber;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.emailstop = emailstop;
        this.icq = icq;
        this.skype = skype;
        this.yahoo = yahoo;
        this.aim = aim;
        this.msn = msn;
        this.phone1 = phone1;
        this.phone2 = phone2;
        this.institution = institution;
        this.department = department;
        this.address = address;
        this.city = city;
        this.country = country;
        this.lang = lang;
        this.calendartype = calendartype;
        this.theme = theme;
        this.timezone = timezone;
        this.firstaccess = firstaccess;
        this.lastaccess = lastaccess;
        this.lastlogin = lastlogin;
        this.currentlogin = currentlogin;
        this.lastip = lastip;
        this.secret = secret;
        this.picture = picture;
        this.url = url;
        this.descriptionformat = descriptionformat;
        this.mailformat = mailformat;
        this.maildigest = maildigest;
        this.maildisplay = maildisplay;
        this.autosubscribe = autosubscribe;
        this.trackforums = trackforums;
        this.timecreated = timecreated;
        this.timemodified = timemodified;
        this.trustbitmask = trustbitmask;
    }
    public MdlUser(String auth, boolean confirmed, boolean policyagreed, boolean deleted, boolean suspended, long mnethostid, String username, String password, String idnumber, String firstname, String lastname, String email, boolean emailstop, String icq, String skype, String yahoo, String aim, String msn, String phone1, String phone2, String institution, String department, String address, String city, String country, String lang, String calendartype, String theme, String timezone, long firstaccess, long lastaccess, long lastlogin, long currentlogin, String lastip, String secret, long picture, String url, String description, byte descriptionformat, boolean mailformat, boolean maildigest, byte maildisplay, boolean autosubscribe, boolean trackforums, long timecreated, long timemodified, long trustbitmask, String imagealt, String lastnamephonetic, String firstnamephonetic, String middlename, String alternatename) {
       this.auth = auth;
       this.confirmed = confirmed;
       this.policyagreed = policyagreed;
       this.deleted = deleted;
       this.suspended = suspended;
       this.mnethostid = mnethostid;
       this.username = username;
       this.password = password;
       this.idnumber = idnumber;
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.emailstop = emailstop;
       this.icq = icq;
       this.skype = skype;
       this.yahoo = yahoo;
       this.aim = aim;
       this.msn = msn;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.institution = institution;
       this.department = department;
       this.address = address;
       this.city = city;
       this.country = country;
       this.lang = lang;
       this.calendartype = calendartype;
       this.theme = theme;
       this.timezone = timezone;
       this.firstaccess = firstaccess;
       this.lastaccess = lastaccess;
       this.lastlogin = lastlogin;
       this.currentlogin = currentlogin;
       this.lastip = lastip;
       this.secret = secret;
       this.picture = picture;
       this.url = url;
       this.description = description;
       this.descriptionformat = descriptionformat;
       this.mailformat = mailformat;
       this.maildigest = maildigest;
       this.maildisplay = maildisplay;
       this.autosubscribe = autosubscribe;
       this.trackforums = trackforums;
       this.timecreated = timecreated;
       this.timemodified = timemodified;
       this.trustbitmask = trustbitmask;
       this.imagealt = imagealt;
       this.lastnamephonetic = lastnamephonetic;
       this.firstnamephonetic = firstnamephonetic;
       this.middlename = middlename;
       this.alternatename = alternatename;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="auth", nullable=false, length=20)
    public String getAuth() {
        return this.auth;
    }
    
    public void setAuth(String auth) {
        this.auth = auth;
    }

    
    @Column(name="confirmed", nullable=false)
    public boolean isConfirmed() {
        return this.confirmed;
    }
    
    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    
    @Column(name="policyagreed", nullable=false)
    public boolean isPolicyagreed() {
        return this.policyagreed;
    }
    
    public void setPolicyagreed(boolean policyagreed) {
        this.policyagreed = policyagreed;
    }

    
    @Column(name="deleted", nullable=false)
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    
    @Column(name="suspended", nullable=false)
    public boolean isSuspended() {
        return this.suspended;
    }
    
    public void setSuspended(boolean suspended) {
        this.suspended = suspended;
    }

    
    @Column(name="mnethostid", nullable=false)
    public long getMnethostid() {
        return this.mnethostid;
    }
    
    public void setMnethostid(long mnethostid) {
        this.mnethostid = mnethostid;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="idnumber", nullable=false)
    public String getIdnumber() {
        return this.idnumber;
    }
    
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    
    @Column(name="firstname", nullable=false, length=100)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", nullable=false, length=100)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="emailstop", nullable=false)
    public boolean isEmailstop() {
        return this.emailstop;
    }
    
    public void setEmailstop(boolean emailstop) {
        this.emailstop = emailstop;
    }

    
    @Column(name="icq", nullable=false, length=15)
    public String getIcq() {
        return this.icq;
    }
    
    public void setIcq(String icq) {
        this.icq = icq;
    }

    
    @Column(name="skype", nullable=false, length=50)
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }

    
    @Column(name="yahoo", nullable=false, length=50)
    public String getYahoo() {
        return this.yahoo;
    }
    
    public void setYahoo(String yahoo) {
        this.yahoo = yahoo;
    }

    
    @Column(name="aim", nullable=false, length=50)
    public String getAim() {
        return this.aim;
    }
    
    public void setAim(String aim) {
        this.aim = aim;
    }

    
    @Column(name="msn", nullable=false, length=50)
    public String getMsn() {
        return this.msn;
    }
    
    public void setMsn(String msn) {
        this.msn = msn;
    }

    
    @Column(name="phone1", nullable=false, length=20)
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    
    @Column(name="phone2", nullable=false, length=20)
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    
    @Column(name="institution", nullable=false)
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    
    @Column(name="department", nullable=false)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    
    @Column(name="address", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="city", nullable=false, length=120)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="country", nullable=false, length=2)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="lang", nullable=false, length=30)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }

    
    @Column(name="calendartype", nullable=false, length=30)
    public String getCalendartype() {
        return this.calendartype;
    }
    
    public void setCalendartype(String calendartype) {
        this.calendartype = calendartype;
    }

    
    @Column(name="theme", nullable=false, length=50)
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }

    
    @Column(name="timezone", nullable=false, length=100)
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    
    @Column(name="firstaccess", nullable=false)
    public long getFirstaccess() {
        return this.firstaccess;
    }
    
    public void setFirstaccess(long firstaccess) {
        this.firstaccess = firstaccess;
    }

    
    @Column(name="lastaccess", nullable=false)
    public long getLastaccess() {
        return this.lastaccess;
    }
    
    public void setLastaccess(long lastaccess) {
        this.lastaccess = lastaccess;
    }

    
    @Column(name="lastlogin", nullable=false)
    public long getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(long lastlogin) {
        this.lastlogin = lastlogin;
    }

    
    @Column(name="currentlogin", nullable=false)
    public long getCurrentlogin() {
        return this.currentlogin;
    }
    
    public void setCurrentlogin(long currentlogin) {
        this.currentlogin = currentlogin;
    }

    
    @Column(name="lastip", nullable=false, length=45)
    public String getLastip() {
        return this.lastip;
    }
    
    public void setLastip(String lastip) {
        this.lastip = lastip;
    }

    
    @Column(name="secret", nullable=false, length=15)
    public String getSecret() {
        return this.secret;
    }
    
    public void setSecret(String secret) {
        this.secret = secret;
    }

    
    @Column(name="picture", nullable=false)
    public long getPicture() {
        return this.picture;
    }
    
    public void setPicture(long picture) {
        this.picture = picture;
    }

    
    @Column(name="url", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="descriptionformat", nullable=false)
    public byte getDescriptionformat() {
        return this.descriptionformat;
    }
    
    public void setDescriptionformat(byte descriptionformat) {
        this.descriptionformat = descriptionformat;
    }

    
    @Column(name="mailformat", nullable=false)
    public boolean isMailformat() {
        return this.mailformat;
    }
    
    public void setMailformat(boolean mailformat) {
        this.mailformat = mailformat;
    }

    
    @Column(name="maildigest", nullable=false)
    public boolean isMaildigest() {
        return this.maildigest;
    }
    
    public void setMaildigest(boolean maildigest) {
        this.maildigest = maildigest;
    }

    
    @Column(name="maildisplay", nullable=false)
    public byte getMaildisplay() {
        return this.maildisplay;
    }
    
    public void setMaildisplay(byte maildisplay) {
        this.maildisplay = maildisplay;
    }

    
    @Column(name="autosubscribe", nullable=false)
    public boolean isAutosubscribe() {
        return this.autosubscribe;
    }
    
    public void setAutosubscribe(boolean autosubscribe) {
        this.autosubscribe = autosubscribe;
    }

    
    @Column(name="trackforums", nullable=false)
    public boolean isTrackforums() {
        return this.trackforums;
    }
    
    public void setTrackforums(boolean trackforums) {
        this.trackforums = trackforums;
    }

    
    @Column(name="timecreated", nullable=false)
    public long getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(long timecreated) {
        this.timecreated = timecreated;
    }

    
    @Column(name="timemodified", nullable=false)
    public long getTimemodified() {
        return this.timemodified;
    }
    
    public void setTimemodified(long timemodified) {
        this.timemodified = timemodified;
    }

    
    @Column(name="trustbitmask", nullable=false)
    public long getTrustbitmask() {
        return this.trustbitmask;
    }
    
    public void setTrustbitmask(long trustbitmask) {
        this.trustbitmask = trustbitmask;
    }

    
    @Column(name="imagealt")
    public String getImagealt() {
        return this.imagealt;
    }
    
    public void setImagealt(String imagealt) {
        this.imagealt = imagealt;
    }

    
    @Column(name="lastnamephonetic")
    public String getLastnamephonetic() {
        return this.lastnamephonetic;
    }
    
    public void setLastnamephonetic(String lastnamephonetic) {
        this.lastnamephonetic = lastnamephonetic;
    }

    
    @Column(name="firstnamephonetic")
    public String getFirstnamephonetic() {
        return this.firstnamephonetic;
    }
    
    public void setFirstnamephonetic(String firstnamephonetic) {
        this.firstnamephonetic = firstnamephonetic;
    }

    
    @Column(name="middlename")
    public String getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    
    @Column(name="alternatename")
    public String getAlternatename() {
        return this.alternatename;
    }
    
    public void setAlternatename(String alternatename) {
        this.alternatename = alternatename;
    }




}


